inherit_from:
 - .rubocop_airbnb.yml


Rails:
 Enabled: true

AllCops:
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/**/*'
    - 'spec/**/*'
    - 'spec/system/*'
    - 'Gemfile'
    - 'app/helpers/*'

Layout/TrailingWhitespace:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NilComparison:
  Enabled: false

